title: Jincheng Tian's Homepage
page-top-title: Jincheng Tian
top-section-bg-text: Computer and Information Engineering
home-subtitle: Jincheng Tian&ensp;|&ensp;田金成
copyright-text: '&copy;  Jincheng Tian 2023-2025. All Rights Reserved.'
